### ISSUE TITLE
新版本闪退

### ISSUE THREAD

**Issue by watermoonchandra** [AttemptD/AfuseKt-release#102]
java.lang.IncompatibleClassChangeError: Class 'java.lang.Object' does not implement interface 'android.window.SplashScreen$OnExitAnimationListener' in call to 'void android.window.SplashScreen$OnExitAnimationListener.onSplashScreenExit(android.window.SplashScreenView)' (declaration of 'android.window.SplashScreen$SplashScreenManagerGlobal' appears in /system/framework/framework.jar!classes4.dex)
	at android.window.SplashScreen$SplashScreenManagerGlobal.dispatchOnExitAnimation(SplashScreen.java:271)
	at android.window.SplashScreen$SplashScreenManagerGlobal.handOverSplashScreenView(SplashScreen.java:258)
	at android.app.ActivityThread.reportSplashscreenViewShown(ActivityThread.java:4459)
	at android.app.ActivityThread.lambda$syncTransferSplashscreenViewTransaction$1(ActivityThread.java:4476)
	at android.app.ActivityThread.$r8$lambda$zFMoOisyD5hrqE37Jh7SYYMQGB8(Unknown Source:0)
	at android.app.ActivityThread$$ExternalSyntheticLambda5.run(Unknown Source:6)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1623)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1632)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1172)
	at android.view.Choreographer.doFrame(Choreographer.java:1072)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1602)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
以上是澎湃OS的第三方应用异常记录信息

**Comment by AttemptD** [comment]
更新10039发自我的 iPhone在 2024年5月27日，18:25，watermoonchandra ***@***.***> 写道：﻿
java.lang.IncompatibleClassChangeError: Class 'java.lang.Object' does not implement interface 'android.window.SplashScreen$OnExitAnimationListener' in call to 'void android.window.SplashScreen$OnExitAnimationListener.onSplashScreenExit(android.window.SplashScreenView)' (declaration of 'android.window.SplashScreen$SplashScreenManagerGlobal' appears in /system/framework/framework.jar!classes4.dex)
at android.window.SplashScreen$SplashScreenManagerGlobal.dispatchOnExitAnimation(SplashScreen.java:271)
at android.window.SplashScreen$SplashScreenManagerGlobal.handOverSplashScreenView(SplashScreen.java:258)
at android.app.ActivityThread.reportSplashscreenViewShown(ActivityThread.java:4459)
at android.app.ActivityThread.lambda$syncTransferSplashscreenViewTransaction$1(ActivityThread.java:4476)
at android.app.ActivityThread.$r8$lambda$zFMoOisyD5hrqE37Jh7SYYMQGB8(Unknown Source:0)
at android.app.ActivityThread$$ExternalSyntheticLambda5.run(Unknown Source:6)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1623)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1632)
at android.view.Choreographer.doCallbacks(Choreographer.java:1172)
at android.view.Choreographer.doFrame(Choreographer.java:1072)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1602)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:224)
at android.os.Looper.loop(Looper.java:318)
at android.app.ActivityThread.main(ActivityThread.java:8653)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
以上是澎湃OS的第三方应用异常记录信息

**Comment by watermoonchandra** [comment]
已更新。已解决。谢谢！

**Comment by watermoonchandra** [comment]
已更新。已解决。谢谢！
